/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Duael (https://sketchfab.com/Duael)
license: SKETCHFAB Editorial (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/planet-tao-seti-prime-cf8884e63f7d4a939bd950565bfb7c24
title: Planet Tao Seti Prime
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PlanetTao(props) {
  const { nodes, materials } = useGLTF("/glb/planet_tao.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.defaultMat}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/planet_tao.glb");
